torneo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('torneoapp.urls','torneo'),namespace='main')),
    path('partido/',include(('torneoapp.urls','torneo'),namespace='partido')),
    path('auth/',include(('torneoapp.urls','torneo'),namespace='auth')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

torneoapp/urls.py
from django.urls import path, URLPattern, URLResolver
from django.conf.urls import url, include
from torneoapp.views import  Home,registroUsuario
from . import views

urlpatterns = [
    path('',views.login,name='login'),
    path('main/home',views.Home,name='home'),
    path('registro',views.registroUsuario,name='registro'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('add/<str:model>',views.add,name='add'),
    path('addid/<str:model>/<str:id>',views.addid,name='addid'),
    path('listar/<str:model>',views.listar,name='listar'),
    path('listarid/<str:model>/<str:id>',views.listarid,name='listarid'),
    path('modify/<str:model>/<str:id>',views.modify,name='modify'),
    path('partido/<str:id>',views.partido,name='partido'),
    path('delete/<str:model>/<str:id>',views.delete,name='delete'),
    path('deleteid/<str:model>/<str:id>/<str:idmol>',views.deleteid,name='deleteid'),
]

torneoapp/forms.py
from django.forms import ModelForm
from django.forms import TextInput, DateInput
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth.models import User
from django import forms
from torneoapp.models import Partido, Equipo, Jugador, Arbitro, Estadio, Patrocinador, Ciudad, Empresa, PersonaNatural, JugadorxEquipo, JugadorxPartido, Evento

class CreateUserForm(UserCreationForm):
    class meta:
        model = User
        fields = ['username','password1','password2']

class CreatePartidoForm(ModelForm):
    class Meta:
        model = Partido
        fields = ['fecha_hora','eq_local','eq_visit','pts_local','pts_visit','estadio','arbitro']
        labels = {'fecha_hora': 'Fecha y Hora (YYYY-MM-DD HH:MM)',
                'eq_local':'Equipo Local',
                'eq_visit':'Equipo Visitante',
                'pts_local':'Goles Equipo Local',
                'pts_visit':'Goles Equipo Visitante',
                'estadio':'Estadio',
                'arbitro':'Árbitro'
                }

class CreateEquipoForm(ModelForm):
    class Meta:
        model = Equipo
        fields = ['nombre','a_creacion','ciudad','patrocinador']
        labels = {'nombre': 'Nombre del equipo',
                'a_creacion':'Año de Creación',
                'ciudad':'Ciudad',
                'patrocinador':'Patrocinador'
                }

class CreateJugadorForm(ModelForm):
    class Meta:
        model = Jugador
        fields = ['nombre','fecha_nacimiento']
        labels = {'nombre': 'Nombre del jugador',
                'fecha_nacimiento':'Fecha de Nacimiento'
                }

class CreateArbitroForm(ModelForm):
    class Meta:
        model = Arbitro
        fields = ['nombre','tutor']
        labels = {'nombre': 'Nombre del Árbitro',
                'tutor':'Tutor'
                }

    def __init__(self, *args, **kwargs):
        super(CreateArbitroForm, self).__init__(*args, **kwargs)
        self.fields['tutor'].required = False

class CreateEstadioForm(ModelForm):
    class Meta:
        model = Estadio
        fields = ['nombre','capacidad','aconstruccion','ciudad']
        labels = {'nombre': 'Nombre del Estadio',
                'capacidad':'Capacidad',
                'aconstruccion':'Año de Construcción',
                'ciudad':'Ciudad'
                }

class CreatePatrocinadorForm(ModelForm):

    class Meta:
        model = Patrocinador
        fields = ['tipo_patrocinador','empresa','personanatural','equipo']
        labels = {'tipo_patrocinador':'Tipo de Patrocinador',
                'empresa': 'Empresa',
                'personanatural':'Persona Natural',
                'equipo':'Equipo'
                }

    def __init__(self, *args, **kwargs):
        super(CreatePatrocinadorForm, self).__init__(*args, **kwargs)
        self.fields['empresa'].required = False
        self.fields['personanatural'].required = False
        self.fields['equipo'].required = False

class CreateCiudadForm(ModelForm):
    class Meta:
        model = Ciudad
        fields = ['nombre','poblacion']
        labels = {'nombre':'Nombre',
                'poblacion': 'Población'
                }

class CreateCiudadForm(ModelForm):
    class Meta:
        model = Ciudad
        fields = ['nombre','poblacion']
        labels = {'nombre':'Nombre',
                'poblacion': 'Población'
                }

class CreateEmpresaForm(ModelForm):
    class Meta:
        model = Empresa
        fields = ['nombre','representante','email','ubicacion']
        labels = {'nombre':'Nombre',
                'representante': 'Representante',
                'email': 'Correo Electrónico',
                'ubicacion': 'Ubicación'
                }

class CreatePersonaNaturalForm(ModelForm):
    class Meta:
        model = PersonaNatural
        fields = ['nombre','telefono']
        labels = {'nombre':'Nombre',
                'telefono': 'Teléfono'
                }

class CreateTransferenciaForm(ModelForm):
    class Meta:
        model = JugadorxEquipo
        fields = ['jugador','equipo','fechaInicio','fechaFin']
        labels = {'fechaInicio':'Fecha de Ingreso',
                'fechaFin': 'Fecha de Salida',
                'equipo': 'Equipo',
                'jugador': 'Jugador'
                }


class CreateJugadorxPartidoForm(ModelForm):
    class Meta:
        model = JugadorxPartido
        fields = ['jugador','partido','min_ingreso','min_salida']
        labels = {'jugador':'Jugador',
                'partido': 'Partido',
                'min_ingreso': 'Minuto de Ingreso',
                'min_salida': 'Minuto de Salida'
                }

class CreateEventoForm(ModelForm):
    class Meta:
        model = Evento
        fields = ['tiempo','tipo_evento','jugadorxpartido','partido','descripcion']
        labels = {'tiempo':'Minuto',
                'tipo_evento': 'Tipo de Evento',
                'jugadorxpartido': 'Ejecutor',
                'partido': 'Partido',
                'descripcion':'Descripción'
                }
    def __init__(self, *args, **kwargs):
        super(CreateEventoForm, self).__init__(*args, **kwargs)
        self.fields['descripcion'].required = False

torneoapp/views.py
from django.shortcuts import render, get_object_or_404 
from django.views import generic
from django.urls import path, reverse
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
import datetime
from .forms import CreateUserForm
from django.db.models import Q
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as do_login
from django.contrib.auth import logout as do_logout
from django.contrib import messages
from torneoapp.models import Partido, Equipo, Jugador, JugadorxEquipo, Arbitro, Estadio, Patrocinador, Ciudad, Empresa, PersonaNatural, JugadorxPartido, Evento
from torneoapp.forms import CreatePartidoForm, CreateEquipoForm, CreateJugadorForm, CreateArbitroForm, CreateEstadioForm, CreatePatrocinadorForm, CreateCiudadForm, CreateEmpresaForm, CreatePersonaNaturalForm, CreateTransferenciaForm, CreateJugadorxPartidoForm, CreateEventoForm

# Create your views here.
INFO = {
        'partido':{
            'form':CreatePartidoForm,
            'name':'Partido',
            'model':Partido,
            'pk':'fecha_hora'
        },
        'equipo':{
            'form':CreateEquipoForm,
            'name':'Equipo',
            'model':Equipo,
            'pk':'nombre'
        },
        'jugador':{
            'form':CreateJugadorForm,
            'name':'Jugador',
            'model':Jugador,
            'pk':'codigo'
        },
        'arbitro':{
            'form':CreateArbitroForm,
            'name':'Árbitro',
            'model':Arbitro,
            'pk':'carne'
        },
        'estadio':{
            'form':CreateEstadioForm,
            'name':'Estadio',
            'model':Estadio,
            'pk':'codigo'
        },
        'patrocinador':{
            'form':CreatePatrocinadorForm,
            'name':'Patrocinador',
            'model':Patrocinador,
            'pk':'id'
        },
        'ciudad':{
            'form':CreateCiudadForm,
            'name':'Ciudad',
            'names':'Ciudades',
            'model':Ciudad,
            'lqset':Ciudad.objects.all().order_by('nombre'),
            'pk':'codigo'
        },
        'empresa':{
            'form':CreateEmpresaForm,
            'name':'Empresa',
            'names':'Empresas',
            'model':Empresa,
            'lqset':Empresa.objects.all().order_by('nombre'),
            'pk':'nombre'
        },
        'personanatural':{
            'form':CreatePersonaNaturalForm,
            'name':'Persona Natural',
            'names':'Personas Naturales',
            'model':PersonaNatural,
            'lqset':PersonaNatural.objects.all().order_by('nombre'),
            'pk':'cedula'
        },
        'transferencia':{
            'form':CreateTransferenciaForm,
            'name':'Transferencia',
            'names':'Transferencias',
            'model':JugadorxEquipo,
            'lqset':JugadorxEquipo.objects.all().order_by('equipo'),
            'pk':'codigo'
        },
         'transferencia2':{
            'form':CreateTransferenciaForm,
            'name':'Transferencia',
            'names':'Transferencias',
            'model':JugadorxEquipo,
            'lqset':JugadorxEquipo.objects.all().order_by('equipo'),
            'pk':'codigo'
        },
        'jugadorxpartido':{
        'form':CreateJugadorxPartidoForm,
        'name':'Jugador del partido',
        'names':'Jugadores del Partido',
        'model':JugadorxPartido,
        'pk':'id'
        },
        'evento':{
        'form':CreateEventoForm,
        'name':'Evento',
        'names':'Eventos',
        'model':Evento,
        'pk':'tiempo'
        },
    }

def registroUsuario(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('auth:login'))

    context = {'form':form}
    return render(request,'main/auth/registro.html',context)

def login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('main:home'))
    else:
        form = AuthenticationForm()
        if request.method == "POST":
            form = AuthenticationForm(data=request.POST)
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                user = authenticate(username=username, password=password)
                if user is not None:
                    do_login(request, user)
                    return HttpResponseRedirect(reverse('main:home'))

        context = {'form':form}
        return render(request, "main/auth/login.html",context)

def Home(request):
    if request.user.is_authenticated:
        partidos = Partido.objects.all().order_by('fecha_hora')
        equipos = Equipo.objects.all()
        jugadores = Jugador.objects.all().order_by('codigo')
        arbitros = Arbitro.objects.all().order_by('carne')
        estadios = Estadio.objects.all().order_by('codigo')
        patrocinadores = Patrocinador.objects.all().order_by('id')
        context = {'partidos':partidos,
        'equipos':equipos,
        'jugadores':jugadores,
        'arbitros':arbitros,
        'estadios':estadios,
        'patrocinadores':patrocinadores,
        }
        return render(request, 'main/home.html',context)
    return HttpResponseRedirect(reverse('auth:login'))

def logout(request):
    do_logout(request)
    return HttpResponseRedirect(reverse('auth:login'))

def add(request,model):
    model_name = INFO[model]['name']
    form = INFO[model]['form']
    if request.method == 'POST':
        form = INFO[model]['form'](request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main:home'))

    context = {'form':form,'model_name':model_name}
    
    return render(request, "main/add.html",context)

def addid(request,model,id):
    model_name = INFO[model]['name']+" "+id
    form = INFO[model]['form']
    print(INFO[model]['name'])

    if INFO[model]['name'] in ('Jugador del partido','Evento'):
        if request.method == 'POST':
            form = INFO[model]['form'](request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('main:partido',kwargs={'id':id}))    
    else:
        if request.method == 'POST':
                form = INFO[model]['form'](request.POST)
                if form.is_valid():
                    form.save()
                    return HttpResponseRedirect(reverse('main:home'))

    context = {'form':form,'model_name':model_name}
    
    return render(request, "main/add.html",context)

def listar(request,model):
    context = {}
    model_name = INFO[model]['names']
    QSETS = {
        'ciudad':Ciudad.objects.all().order_by('nombre'),
        'empresa':Empresa.objects.all().order_by('nombre'),
        'personanatural':PersonaNatural.objects.all().order_by('nombre'),
        'transferencia':JugadorxEquipo.objects.all().order_by('equipo')
    }
    queryset = QSETS[model]
    context = {'queryset':queryset,'model_name':model_name,'model':model}
    
    return render(request, "main/listar.html",context)

def listarid(request,model,id):
    context = {}
    queryset = ""

    if model in 'jugadorxpartido':
        queryset = JugadorxPartido.objects.filter(partido=id)
        model_name = INFO[model]['names']
        context = {'queryset':queryset,'model_name':model_name,'model':model,'idmol':id}
    elif model in  'transferencia2':
        queryset = JugadorxEquipo.objects.filter(jugador=id)
        model_name = INFO['transferencia']['names']
        name = Jugador.objects.get(pk=id).nombre
        context = {'queryset':queryset,'model_name':model_name,'model':'transferencia2','idmol':id,'name':name}

    return render(request, "main/listar.html",context)

def modify(request,model,id):
    model_name = INFO[model]['name']
    obj= get_object_or_404(INFO[model]['model'], pk=id)
    print(obj)
    form = INFO[model]['form'](request.POST or None, instance= obj)

    if request.method == 'POST':
        if form.is_valid():
            if INFO[model]['name'] in 'partido':
                INFO[model]['model'].objects.get(pk=id).delete()
                
            obj=form.save(commit=False)
            obj.save()
            messages.success(request, "successfully updated")
            context = {'form':form,'model_name':model_name,'id':id}
            return HttpResponseRedirect(reverse('main:home'))
        else:
            context= {'form': form,
            'error': 'The form was not updated successfully. Please enter in a title and content'}
            return render(request, "main/modify.html",context)

    context = {'form':form,'model_name':model_name,'id':id}
    return render(request, "main/modify.html",context)

def delete(request,model,id):
    model_name = INFO[model]['name']

    if request.method == 'POST':
        print("if")
        INFO[model]['model'].objects.get(pk=id).delete()
        return HttpResponseRedirect(reverse('main:home'))
    else:
        print("else")
        context = {'model_name':model_name,'id':id}
        return render(request, "main/delete.html",context)

    context = {'model_name':model_name,'id':id}
    return render(request, "main/delete.html",context)

def deleteid(request,model,id,idmol):
    model_name = INFO[model]['name']

    if request.method == 'POST':
        print("if")
        INFO[model]['model'].objects.get(pk=id).delete()
        if model == 'jugadorxpartido':
            return HttpResponseRedirect(reverse('main:partido',kwargs={'id':idmol}))
        else:
            return HttpResponseRedirect(reverse('main:home'))
    else:
        print("else")
        context = {'model_name':model_name,'id':id}

torneoapp/templates/main/partido.html
{% extends 'style.html' %}
{% load tz %}
{% block body %}
<html>
    <head>

        <style>
            #divbo{
            display: flex;
            justify-content: center;
            background-color: rgb(255, 240, 158);
            padding-top: 120px;
            margin-bottom: 60px;
            }
        </style>

        <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
            <header class="mdl-layout__header"> 
                <div class="mdl-layout__header-row">
                    <table style="height:100%; width: 100%;">
                        <tr style="height: 100%;">
                            <td>
                                <a href="{% url 'main:home' %}" style="text-decoration:none ; color: black; font-weight: 500; font-size: 25px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;" class="mdl-layout-title">
                                    Torneo de Fútbol: Partido {{ eq_local }} vs. {{ eq_visit }}
                                </a>
                            </td>
                            <td style="text-align: right; padding-right: 10px;">
                                <a href="{% url 'main:logout' %}" style="background-color: transparent;" class="mdl-button--icon mdl-button mdl-js-button mdl-js-ripple-effect" style="text-decoration:none ; color: black; font-weight: 500; font-size: 25px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;" class="mdl-layout-title">
                                    <i class="material-icons">logout</i>
                                </a>
                            </td>
                        </tr>
                    </table>
                </div>
            </header>
            <title>{{ eq_local }} vs. {{ eq_visit }} </title>
        </div>
    </head>

    <body>
        <div style="padding-top: 80px;" id="centerdiv">
            <p style="margin-top: 20px;" id="ptitle">Partido</p>
            <p style="margin-top: 20px;" id="ptitle">{{ eq_local }} vs. {{ eq_visit }}</p>
            <hr style="margin: auto; margin-top: 20px; border-color: black;" width="70%">

            <p style="margin-top: 30px;" id="ptitle">Ficha Técnica</p>
            <div id="divtab">
                <table id="parttable" class="mdl-data-table mdl-js-data-table mdl-shadow--2dp" style="align-self: center;"> 
                    <tr><td style="text-align: center; font-size: 20px;"><b>Fecha</b><br>{{ fecha |timezone:"America/Bogota"|date:'F j, Y - P'}}</td></tr>
                </table>
            </div>
            <div id="divtab">
                <table id="parttable" class="mdl-data-table mdl-js-data-table mdl-shadow--2dp" style="align-self: center;"> 
                    <tr><td style="text-align: center; font-size: 20px;"><b>Árbitro</b><br>{{ arbitro }}</td></tr>
                </table>
            </div>
            <div style="padding-top: 10px;" id="divtab">
                <table id="parttable" class="mdl-data-table mdl-js-data-table mdl-shadow--2dp" style="align-self: center;"> 
                    <tr><td style="text-align: center; font-size: 20px;"><b>Marcador
                    <tr><td style="text-align: center; font-size: 20px;">
                        {{eq_local }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{pts_local}} - {{pts_visit}}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{eq_visit}}
                    </td>
                    </tr>
                </table>
            </div>
            <div style="padding-top: 10px;" id="divtab">
                <table id="parttable" class="mdl-data-table mdl-js-data-table mdl-shadow--2dp" style="align-self: center;"> 
                    <tr><td style="text-align: center; font-size: 20px; background-color: rgb(75, 132, 255); color: white;"><b>{% if ganador != 'Empate' %}Ganador{% else %} Resultado {% endif %}</b>
                    <tr><td style="text-align: center; font-size: 20px; background-color: rgb(134, 173, 255);"><b>{{ ganador }}</b></td>
                    </tr>
                </table>
            </div>

            <hr style="margin: auto; margin-top: 40px; border-color: black;" width="70%">
            <p style="margin-top: 30px;" id="ptitle">Jugadores</p>

            <div>
                <div style="padding-top: 10px;" id="divtab">
                    <table style="align-self: center; width: 50%;">
                        <thead>
                            <tr>
                                <th style="font-size: 20px; width: 40%;">{{eq_local}}</th>
                                <th style="text-align: center; width: 20%;"></th>
                                <th style="font-size: 20px; width: 40%;">{{eq_visit}}</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <div style="display: flex; justify-content: center;">
                                    <table id="intable" style="align-self: center; width: 100%; margin-top: 20px;" class="mdl-data-table mdl-js-data-table mdl-shadow--2dp"> 
                                            {% for jugador in j_local %}
                                            <tr><td style="text-align: center;">{{ jugador }}</td></tr>
                                            {% empty %}
                                            <tr><td style="text-align: center;">No hay jugadores de este equipo<br>registrados para este partido</td></tr>
                                            {% endfor %}
                                    </table>
                                    </div>
                                </td>
                                <td></td>
                                <td>
                                    <div style="display: flex; justify-content: center;">
                                        <table id="intable" style="align-self: center; width: 100%; margin-top: 20px;" class="mdl-data-table mdl-js-data-table mdl-shadow--2dp"> 
                                            {% for jugador in j_visit %}
                                            <tr><td style="text-align: center;">{{ jugador }}</td></tr>
                                            {% empty %}
                                            <tr><td style="text-align: center;">No hay jugadores de este equipo<br>registrados para este partido</td></tr>
                                            {% endfor %}
                                        </table>
                                    </div>
                                </div>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td style="text-align: center; padding-top: 20px;">
                                    <a id="fbuttons" title="Agregar Jugador al Partido" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-shadow--2dp" href="{% url 'main:addid' 'jugadorxpartido' fecha %}"> 
                                        <i class="material-icons">add</i>
                                    </a>
                                    <a style="margin-left: 10px; margin-right: 10px;" href="">
                                    </a>
                                    <a id="fbuttons" title="Lista de jugadores del Partido" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-shadow--2dp" href="{% url 'main:listarid' 'jugadorxpartido' fecha %}"> 
                                        <i class="material-icons">list</i>
                                    </a>
                                </td>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <hr style="margin: auto; margin-top: 40px; border-color: black;" width="70%">
                <p style="margin-top: 30px;" id="ptitle">Eventos</p>
                
                <div style="display: flex; justify-content: center;">
                    <div id="divtab"  style="width: 70%;">
                        <table style="width: 100%;"> 
                            <tr>
                                <td>
                                    <table style="width: 100%;" id="intable" class="mdl-data-table mdl-js-data-table mdl-shadow--2dp" style="align-self: center; width: 100%;"> 
                                        <thead style="background-color: rgb(201, 201, 201);">
                                            <tr>
                                                <th id="thsty" style="text-align: center;" class="mdl-color-text--black mdl-data-table__cell--non-numeric">Minuto</th>
                                                <th id="thsty" style="text-align: center;" class="mdl-color-text--black mdl-data-table__cell--non-numeric">Evento</th>
                                                <th id="thsty" style="text-align: center;" class="mdl-color-text--black mdl-data-table__cell--non-numeric">Ejecutor</th>
                                                <th id="thsty" style="text-align: center;" class="mdl-color-text--black mdl-data-table__cell--non-numeric">Descripción</th>
                                                <th id="thsty" style="text-align: center;" class="mdl-color-text--black mdl-data-table__cell--non-numeric">Acciones</th>
                                            </tr>
                                        </thead>

                                        <tbody>
                                        {% for evento in eventos %}
                                            <tr>
                                                <td id="tdsty" style="text-align: center;" class="mdl-data-table__cell--non-numeric">
                                                    {{ evento.tiempo }}
                                                </td>
                                                <td id="tdsty" style="text-align: center;" class="mdl-data-table__cell--non-numeric">
                                                    {{ evento.tipo_evento }}
                                                </td>
                                                <td id="tdsty" style="text-align: center;" class="mdl-data-table__cell--non-numeric">
                                                    {{ evento.jugadorxpartido.jugador }}
                                                </td>
                                                <td id="tdsty" style="text-align: center;" class="mdl-data-table__cell--non-numeric">
                                                    {% if evento.descripcion != None %}{{ evento.descripcion }}{% else %} - {% endif %}
                                                </td>
                                                <td id="tdsty" style="text-align: center;" class="mdl-data-table__cell--non-numeric">
                                                    <a href="{% url 'main:modify' 'evento' evento.codigo %}" title="Editar Registro" style="background-color: transparent;" class="mdl-button--icon mdl-button mdl-js-button mdl-js-ripple-effect" style="text-decoration:none ; color: black; font-weight: 500; font-size: 25px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;" class="mdl-layout-title">
                                                        <i id="iconsm-centered" class="material-icons">edit</i>
                                                    </a>
                                                    <a href="{% url 'main:deleteid' 'evento' evento.codigo fecha %}" title="Eliminar Registro" style="background-color: transparent;" class="mdl-button--icon mdl-button mdl-js-button mdl-js-ripple-effect" style="text-decoration:none ; color: black; font-weight: 500; font-size: 25px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;" class="mdl-layout-title">
                                                        <i id="iconsm-centered" class="material-icons">delete</i>
                                                    </a>
                                                </td>
                                            </tr>
                                        {% empty %}
                                            <tr>
                                                <td id="tdsty" style="text-align: center;" class="mdl-data-table__cell--non-numeric" colspan="5">
                                                    No hay eventos registrados para este partido.
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>

                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td style="text-align: center; padding-bottom: 20px;">
                                <a id="fbuttons" title="Agregar Evento al Partido" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-shadow--2dp" href="{% url 'main:addid' 'evento' fecha %}"> 
                                    <i class="material-icons">add</i>
                                </a>
                                </td>
                            </tr>
                        </table>    
                    </div>
                </div>
            
                
        </div>

            
    </body>
</html>
{% endblock body %}